---

# Python for Network Engineers Class 6 Exercise 1
# Using Ansible, configure three VLANs on the Arista switch
# specifying both the VLAN IDs and the VLAN names. For the VLAN
# IDs randomly pick three numbers between 100 and 999.

- name: Create Arista VLANs
  hosts: arista
  
  tasks:
    - name: create VLANs
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {vlan_name: red, vlan_id: 100}
        - {vlan_name: white, vlan_id: 200}
        - {vlan_name: blue, vlan_id: 300}

