---

#Python for Network Engineers Week 6 Exercise 3
#Use Ansible to configure your primary Ethernet interface:
#
#switchport mode:        trunk
#trunk native VLAN:      VLAN1
#trunk allowed VLANs:    <the three created in exercise 1>

- name: Configure Arista Trunk
  hosts: arista

  tasks:
    - name: Configure Ethernet4 as trunk
      eos_switchport: name=Ethernet4 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=100,200,300
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

