---

#Python for Network Engineers Week 6 Exercise 5
#Use the cisco_file_transfer.py module to transfer a small file to
#the Cisco pynet-rtr1 router.

- name: Ansible-Cisco file transfer
  hosts: pynet-rtr1
  gather_facts: False

  tasks:
  - name: File transfer
    cisco_file_transfer:
      source_file="/home/kokumura/ANSIBLE/cisco_file.txt"
      dest_file=cisco_file.txt
      overwrite=true
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}

